parse_config:
  zmk_preamble: "#include <zmk-helpers/key-labels/totem.h>"
  zmk_additional_includes:
    - "modules/helpers/include"

draw_config:
  footer_text: "NeoXavier/zmk-config-totem"
  dark_mode: auto
